# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d13ed25c42418b97a1f314621878b958634ec338b725c92ebebe2ed6f728cda371c60cf6df50340607a3341f51eb7794f4763b3dcd7cf92be98e2646f24767

test:
  secret_key_base: 8bb26f9d527652eea736e50046d1a676e516ff68f937baf1dde87cef02c42fb2b6fb4842d33214eb65902b9d1c726a0f2017cc2205bf0b5128eaba0d1cd44628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
